### ISSUE TITLE
Cell-type signature data

### ISSUE THREAD

**Issue by ashipde** [tabbassidaloii/HumanMuscleTranscriptomeAtlasAnalyses#1]
Hello, I am interested in using your cell composition analysis [method](https://github.com/tabbassidaloii/HumanMuscleTranscriptomeAtlasAnalyses/blob/main/dataAnalyses/2.cellTypeComposition.Rmd) with my human skeletal muscle biopsy data. Is it possible for me to get the marker/signature data that is used in your method (_cellTypeMarkers.RData_)? Thank you.

**Comment by tabbassidaloii** [comment]
Hi, thank you for reaching out.
The list of markers can be found [here](https://elifesciences.org/articles/80500/figures#supp2).

**Comment by ashipde** [comment]
Thank you! I should have checked carefully.

**Comment by tabbassidaloii** [comment]
No worries.
